version: '3'
services:
    dhis:
        image: dhis2/core:2.32.5
        ports:
            - "8080:8080"
        volumes:
            - /home/jaime/uio/docker/jaime-dhis2-docker/conf/dhis.conf:/DHIS2_home/dhis.conf
        environment:
            - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
        depends_on:
            - db
    db:
        image: mdillon/postgis:10-alpine
        ports:
            - "5432:5432"
        volumes:
            - /home/jaime/uio/dbs/2.32/:/docker-entrypoint-initdb.d/
        command: postgres -c max_locks_per_transaction=96
        environment:
            - POSTGRES_PASSWORD=dhis
            - POSTGRES_USER=dhis
            - POSTGRES_DB=dhis2
